// Code generated by MockGen. DO NOT EDIT.
// Source: client/grpc/grpc_generated_v2/health_grpc.pb.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	grpc_generated_v2 "github.com/Trendyol/go-triton-client/client/grpc/grpc_generated_v2"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockHealthClient is a mock of HealthClient interface.
type MockHealthClient struct {
	ctrl     *gomock.Controller
	recorder *MockHealthClientMockRecorder
}

// MockHealthClientMockRecorder is the mock recorder for MockHealthClient.
type MockHealthClientMockRecorder struct {
	mock *MockHealthClient
}

// NewMockHealthClient creates a new mock instance.
func NewMockHealthClient(ctrl *gomock.Controller) *MockHealthClient {
	mock := &MockHealthClient{ctrl: ctrl}
	mock.recorder = &MockHealthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthClient) EXPECT() *MockHealthClientMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthClient) Check(ctx context.Context, in *grpc_generated_v2.HealthCheckRequest, opts ...grpc.CallOption) (*grpc_generated_v2.HealthCheckResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Check", varargs...)
	ret0, _ := ret[0].(*grpc_generated_v2.HealthCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockHealthClientMockRecorder) Check(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthClient)(nil).Check), varargs...)
}

// MockHealthServer is a mock of HealthServer interface.
type MockHealthServer struct {
	ctrl     *gomock.Controller
	recorder *MockHealthServerMockRecorder
}

// MockHealthServerMockRecorder is the mock recorder for MockHealthServer.
type MockHealthServerMockRecorder struct {
	mock *MockHealthServer
}

// NewMockHealthServer creates a new mock instance.
func NewMockHealthServer(ctrl *gomock.Controller) *MockHealthServer {
	mock := &MockHealthServer{ctrl: ctrl}
	mock.recorder = &MockHealthServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthServer) EXPECT() *MockHealthServerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthServer) Check(arg0 context.Context, arg1 *grpc_generated_v2.HealthCheckRequest) (*grpc_generated_v2.HealthCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", arg0, arg1)
	ret0, _ := ret[0].(*grpc_generated_v2.HealthCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockHealthServerMockRecorder) Check(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthServer)(nil).Check), arg0, arg1)
}

// mustEmbedUnimplementedHealthServer mocks base method.
func (m *MockHealthServer) mustEmbedUnimplementedHealthServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedHealthServer")
}

// mustEmbedUnimplementedHealthServer indicates an expected call of mustEmbedUnimplementedHealthServer.
func (mr *MockHealthServerMockRecorder) mustEmbedUnimplementedHealthServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedHealthServer", reflect.TypeOf((*MockHealthServer)(nil).mustEmbedUnimplementedHealthServer))
}

// MockUnsafeHealthServer is a mock of UnsafeHealthServer interface.
type MockUnsafeHealthServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeHealthServerMockRecorder
}

// MockUnsafeHealthServerMockRecorder is the mock recorder for MockUnsafeHealthServer.
type MockUnsafeHealthServerMockRecorder struct {
	mock *MockUnsafeHealthServer
}

// NewMockUnsafeHealthServer creates a new mock instance.
func NewMockUnsafeHealthServer(ctrl *gomock.Controller) *MockUnsafeHealthServer {
	mock := &MockUnsafeHealthServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeHealthServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeHealthServer) EXPECT() *MockUnsafeHealthServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedHealthServer mocks base method.
func (m *MockUnsafeHealthServer) mustEmbedUnimplementedHealthServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedHealthServer")
}

// mustEmbedUnimplementedHealthServer indicates an expected call of mustEmbedUnimplementedHealthServer.
func (mr *MockUnsafeHealthServerMockRecorder) mustEmbedUnimplementedHealthServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedHealthServer", reflect.TypeOf((*MockUnsafeHealthServer)(nil).mustEmbedUnimplementedHealthServer))
}
