// Code generated by MockGen. DO NOT EDIT.
// Source: client/grpc/grpc_generated_v2/health.pb.go
//
// Generated by this command:
//
//	mockgen -source=client/grpc/grpc_generated_v2/health.pb.go -destination=mocks/mock_health.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
